[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "yfin-mcp"
version = "0.1.0"
dependencies = [
    "mcp",
    "yfinance>=0.2",
    "pandas",
]

[project.scripts]
yfin-mcp = "yfin_mcp.server:main"
